### ISSUE TITLE
can't close the backbee toolbar closing the log in pop in

### ISSUE THREAD

**Issue by clementbonfils** [backbee/BbCoreJs#522] opened 2015-05-18 09:42 UTC
clicking on the cross of the log in pop in, i can't get back to the regular front office

**Comment by fkroockmann** [comment] 2015-05-19 12:15
The problem is in "ToolbarBundle".
In bbtoolbar.twig, we need to verify if the session is expired too for add "data-autostart" in DOM

ping @eric-chau

**Comment by eric-chau** [comment] 2015-05-19 23:25
@fkroockmann, I created a PR into ``backbee/backbee`` to resolve problem due to session expiration but it does not resolve issue about closing the login popin cause the token is still valid. You should do something like sending a request to destroy the session so user will be disconnected properly like we actually do with the Logout button.

**Closed** 2015-05-22 14:52 UTC
Labels: Fixed, To test
